/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abrir_texto;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author gerar
 */
public class frm_abrir_txt extends javax.swing.JFrame {
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileOutputStream entrada;
    FileOutputStream salida;
    /**
     * Creates new form frm_abrir_txt
     */
    public frm_abrir_txt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area1 = new javax.swing.JTextArea();
        btn_abrir = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_procesar = new javax.swing.JButton();
        lbl_longitud_del_texto = new javax.swing.JLabel();
        lbl_total_de_palabras = new javax.swing.JLabel();
        lbl_primer_letra_del_texto = new javax.swing.JLabel();
        lbl_ultima_letra_del_texto = new javax.swing.JLabel();
        lbl_letra_central_del_texto = new javax.swing.JLabel();
        lbl_primera_palabra = new javax.swing.JLabel();
        lbl_palabra_central = new javax.swing.JLabel();
        lbl_ultima_palabra = new javax.swing.JLabel();
        lbl_rep_a = new javax.swing.JLabel();
        lbl_rep_e = new javax.swing.JLabel();
        lbl_rep_i = new javax.swing.JLabel();
        lbl_rep_o = new javax.swing.JLabel();
        lbl_rep_u = new javax.swing.JLabel();
        lbl_palabras_par = new javax.swing.JLabel();
        lbl_palabras_impar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area2 = new javax.swing.JTextArea();
        btn_limpiar = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_area1.setColumns(20);
        txt_area1.setRows(5);
        jScrollPane1.setViewportView(txt_area1);

        btn_abrir.setText("Abrir");
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_procesar.setText("Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        lbl_longitud_del_texto.setText("Longitud del texto:");

        lbl_total_de_palabras.setText("Total de palabras:");

        lbl_primer_letra_del_texto.setText("Primer letra del texto:");

        lbl_ultima_letra_del_texto.setText("Ultima letra del texto:");

        lbl_letra_central_del_texto.setText("Letra central del texto:");

        lbl_primera_palabra.setText("Primera palabra:");

        lbl_palabra_central.setText("Palabra central:");

        lbl_ultima_palabra.setText("Ultima palabra:");

        lbl_rep_a.setText("Repeticiones de \"A\", \"a\" ó \"á\":");

        lbl_rep_e.setText("Repeticiones de \"E\", \"e\" ó \"é\":");

        lbl_rep_i.setText("Repeticiones de \"I\", \"i\" ó \"í\":");

        lbl_rep_o.setText("Repeticiones de \"O\", \"o\" ó \"ó\":");

        lbl_rep_u.setText("Repeticiones de \"U\", \"u\" ó \"ú\":");

        lbl_palabras_par.setText("Palabras con cantidad de caracteres par:");

        lbl_palabras_impar.setText("Palabras con cantidad de caracteres impar:");

        txt_area2.setColumns(20);
        txt_area2.setRows(5);
        jScrollPane3.setViewportView(txt_area2);

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_palabra_central)
                            .addComponent(lbl_letra_central_del_texto)
                            .addComponent(lbl_ultima_letra_del_texto)
                            .addComponent(lbl_primer_letra_del_texto)
                            .addComponent(lbl_total_de_palabras)
                            .addComponent(lbl_longitud_del_texto)
                            .addComponent(lbl_primera_palabra)
                            .addComponent(lbl_ultima_palabra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_palabras_impar)
                            .addComponent(lbl_palabras_par, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_rep_u, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_rep_o, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_rep_i, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_rep_e, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_rep_a, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_abrir)
                    .addComponent(btn_guardar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_procesar)
                    .addComponent(btn_limpiar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_longitud_del_texto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_de_palabras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_primer_letra_del_texto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_ultima_letra_del_texto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_letra_central_del_texto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_primera_palabra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_palabra_central))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_rep_a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_rep_e)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_rep_i)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_rep_o)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_rep_u)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_palabras_par)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_palabras_impar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ultima_palabra)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null,"Abrir")==JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    String documento = AbrirArchivo (archivo);
                    this.txt_area1.setText(documento);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");
                }
            }
        }
    }//GEN-LAST:event_btn_abrirActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null, "guardar")==JFileChooser.APPROVE_OPTION){
            if(archivo.getName().endsWith("txt")){
                String Documento = txt_area1.getName();
                String mensaje=GuardarArchivo(archivo, Documento);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Archivo no compatible");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Guardar Documento de texto");
            }
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        // TODO add your handling code here:
        this.lbl_longitud_del_texto.setText("Longitud del texto:");
        this.lbl_total_de_palabras.setText("Total de palabras:");
        this.lbl_primer_letra_del_texto.setText("Primer letra del texto:");
        this.lbl_ultima_letra_del_texto.setText("Ultima letra del texto:");
        this.lbl_letra_central_del_texto.setText("Letra central del texto:");
        this.lbl_primera_palabra.setText("Primera palabra:");
        this.lbl_palabra_central.setText("Palabra central:");
        this.lbl_ultima_palabra.setText("Ultima palabra:");
        this.lbl_rep_a.setText("Repeticiones de \"A\", \"a\" ó \"á\":");
        this.lbl_rep_e.setText("Repeticiones de \"E\", \"e\" ó \"é\":");
        this.lbl_rep_i.setText("Repeticiones de \"I\", \"i\" ó \"í\":");
        this.lbl_rep_o.setText("Repeticiones de \"O\", \"o\" ó \"ó\":");
        this.lbl_rep_u.setText("Repeticiones de \"U\", \"u\" ó \"ú\":");
        this.lbl_palabras_par.setText("Palabras con cantidad de caracteres par:");
        this.lbl_palabras_impar.setText("Palabras con cantidad de caracteres impar:");
        this.txt_area2.setText("");
        
        
        String doc = this.txt_area1.getText();
        
        //Longitud del Texto
        int longitudDelTexto = doc.length();
        this.lbl_longitud_del_texto.setText(lbl_longitud_del_texto.getText() + " " + longitudDelTexto);
        
        //Total de palabras
        StringTokenizer numPal = new StringTokenizer (doc);
        this.lbl_total_de_palabras.setText(lbl_total_de_palabras.getText() + " " + numPal.countTokens());
        
        //Primer letra del texto
        char PrimerLetra = doc.charAt(0);
        this.lbl_primer_letra_del_texto.setText(lbl_primer_letra_del_texto.getText() + " " + PrimerLetra);
        
        //Ultima letra del texto
        int NumUltLetra=doc.length();
        char UltimaLetra = doc.charAt(NumUltLetra - 1);
        this.lbl_ultima_letra_del_texto.setText(lbl_ultima_letra_del_texto.getText() + " " + UltimaLetra);
        
        //Letra central del texto
        int NumCentLetra=doc.length();
        char LetraCent = doc.charAt((NumCentLetra - 1)/2);
        this.lbl_letra_central_del_texto.setText(lbl_letra_central_del_texto.getText() + " " + LetraCent);
        
        //Primera palabra
        StringTokenizer PrimeraPalabra = new StringTokenizer (doc);
        this.lbl_primera_palabra.setText(lbl_primera_palabra.getText() + " " + PrimeraPalabra.nextToken());
        
        //Palabra central
        String PalabraCentral = null;
        StringTokenizer tokenPalabra = new StringTokenizer (doc);
        int midd;
        int count = tokenPalabra.countTokens();
        midd = count/2;
        while (midd < tokenPalabra.countTokens()) {
            PalabraCentral = tokenPalabra.nextToken();
        }
        this.lbl_palabra_central.setText(lbl_palabra_central.getText() + " " + PalabraCentral);
        
        //Ultima palabra
        String UltimaPalabraL = null;
        StringTokenizer UltimaPalabra = new StringTokenizer (doc);
        while (UltimaPalabra.hasMoreTokens()) {
            UltimaPalabraL = UltimaPalabra.nextToken();
        }
        this.lbl_ultima_palabra.setText(lbl_ultima_palabra.getText() + " " + UltimaPalabraL);
        
        //Cantidad de palabras par
        int contadorPar = 0;
        String PalabraPar = null;
        StringTokenizer PalabraNumPar = new StringTokenizer (doc);
        while (PalabraNumPar.hasMoreTokens()) {
            PalabraPar = PalabraNumPar.nextToken();
            if(PalabraPar.length()%2==0){
                contadorPar++;
            }
        }
        this.lbl_palabras_par.setText(lbl_palabras_par.getText() + " " + contadorPar);
        
        //Cantidad de palabras impar
        int contadorImpar = 0;
        String PalabraImpar = null;
        StringTokenizer PalabraNumImpar = new StringTokenizer (doc);
        while (PalabraNumImpar.hasMoreTokens()) {
            PalabraImpar = PalabraNumImpar.nextToken();
            if(PalabraImpar.length()%2!=0){
                contadorImpar++;
            }
        }
        this.lbl_palabras_impar.setText(lbl_palabras_impar.getText() + " " + contadorImpar);
        
        //repeticiones de la letra "A"
        int as = 0;
        
        for (int i=0;i<doc.length();i++){
            if ((doc.charAt(i) == 'a') || (doc.charAt(i) == 'A') || (doc.charAt(i) == 'á')){
                as ++;
            }
        }
        this.lbl_rep_a.setText(lbl_rep_a.getText() + " " + as);
        
        //repeticiones de la letra "E"
        int es = 0;
        
        for (int i=0;i<doc.length();i++){
            if ((doc.charAt(i) == 'e') || (doc.charAt(i) == 'E') || (doc.charAt(i) == 'é')){
                es ++;
            }
        }
        this.lbl_rep_e.setText(lbl_rep_e.getText() + " " + es);
        
        //repeticiones de la letra "I"
        int is = 0;
        
        for (int i=0;i<doc.length();i++){
            if ((doc.charAt(i) == 'i') || (doc.charAt(i) == 'I') || (doc.charAt(i) == 'í')){
                is ++;
            }
        }
        this.lbl_rep_i.setText(lbl_rep_i.getText() + " " + is);
        
        //repeticiones de la letra "O"
        int os = 0;
        
        for (int i=0;i<doc.length();i++){
            if ((doc.charAt(i) == 'o') || (doc.charAt(i) == 'O') || (doc.charAt(i) == 'ó')){
                os ++;
            }
        }
        this.lbl_rep_o.setText(lbl_rep_o.getText() + " " + os);
        
        //repeticiones de la letra "U"
        int us = 0;
        
        for (int i=0;i<doc.length();i++){
            if ((doc.charAt(i) == 'u') || (doc.charAt(i) == 'U') || (doc.charAt(i) == 'ú')){
                us ++;
            }
        }
        this.lbl_rep_u.setText(lbl_rep_u.getText() + " " + us);
        
        //convertir a murcielago
        for(int i=0; i<doc.length(); i++){

                //Con estos if comprobamos las letras que se ingresan
                switch (doc.charAt(i)) {
                    case 'M':
                    case 'm':
                        this.txt_area2.setText(this.txt_area2.getText() + "0");
                        break;
                    case 'U':
                    case 'u':
                        this.txt_area2.setText(this.txt_area2.getText() + "1");
                        break;
                    case 'R':
                    case 'r':
                        this.txt_area2.setText(this.txt_area2.getText() + "2");
                        break;
                    case 'C':
                    case 'c':
                        this.txt_area2.setText(this.txt_area2.getText() + "3");
                        break;
                    case 'I':
                    case 'i':
                        this.txt_area2.setText(this.txt_area2.getText() + "4");
                        break;
                    case 'E':
                    case 'e':
                        this.txt_area2.setText(this.txt_area2.getText() + "5");
                        break;
                    case 'L':
                    case 'l':
                        this.txt_area2.setText(this.txt_area2.getText() + "6");
                        break;
                    case 'A':
                    case 'a':
                        this.txt_area2.setText(this.txt_area2.getText() + "7");
                        break;
                    case 'G':
                    case 'g':
                        this.txt_area2.setText(this.txt_area2.getText() + "8");
                        break;
                    case 'O':
                    case 'o':
                        this.txt_area2.setText(this.txt_area2.getText() + "9");
                        break;
                    default:
                        this.txt_area2.setText(this.txt_area2.getText() + doc.charAt(i));
                        break;
                }// end switch


            }//end for de la frase
        
        
        
        
        
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        this.lbl_longitud_del_texto.setText("Longitud del texto:");
        this.lbl_total_de_palabras.setText("Total de palabras:");
        this.lbl_primer_letra_del_texto.setText("Primer letra del texto:");
        this.lbl_ultima_letra_del_texto.setText("Ultima letra del texto:");
        this.lbl_letra_central_del_texto.setText("Letra central del texto:");
        this.lbl_primera_palabra.setText("Primera palabra:");
        this.lbl_palabra_central.setText("Palabra central:");
        this.lbl_ultima_palabra.setText("Ultima palabra:");
        this.lbl_rep_a.setText("Repeticiones de \"A\", \"a\" ó \"á\":");
        this.lbl_rep_e.setText("Repeticiones de \"E\", \"e\" ó \"é\":");
        this.lbl_rep_i.setText("Repeticiones de \"I\", \"i\" ó \"í\":");
        this.lbl_rep_o.setText("Repeticiones de \"O\", \"o\" ó \"ó\":");
        this.lbl_rep_u.setText("Repeticiones de \"U\", \"u\" ó \"ú\":");
        this.lbl_palabras_par.setText("Palabras con cantidad de caracteres par:");
        this.lbl_palabras_impar.setText("Palabras con cantidad de caracteres impar:");
        this.txt_area1.setText("");
        this.txt_area2.setText("");
        
    }//GEN-LAST:event_btn_limpiarActionPerformed
    //btn_procesarActionPerformed
    
    public String AbrirArchivo(File archivo){
        String documento = "";
        //String test = " AAA";
        try{
            FileInputStream entrada = new FileInputStream(archivo);
            int ascci;
            while ((ascci = entrada.read())!=-1){
                char caracter = (char)ascci;
                documento += caracter;
            }
            //documento += test;
            
            
        }
        catch(IOException e) {
            
        }
        
        return documento;
    }
    
    public String GuardarArchivo (File archivo, String documento){
        String mensaje = null;
        try{
            FileOutputStream salida = new FileOutputStream(archivo);
            byte[] bytxt= documento.getBytes();
            salida.write(bytxt);
            mensaje = "Archivo Guardado";
        }
        catch (IOException e){
            
        }
        return mensaje;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_abrir_txt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_abrir_txt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_abrir_txt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_abrir_txt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_abrir_txt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_procesar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_letra_central_del_texto;
    private javax.swing.JLabel lbl_longitud_del_texto;
    private javax.swing.JLabel lbl_palabra_central;
    private javax.swing.JLabel lbl_palabras_impar;
    private javax.swing.JLabel lbl_palabras_par;
    private javax.swing.JLabel lbl_primer_letra_del_texto;
    private javax.swing.JLabel lbl_primera_palabra;
    private javax.swing.JLabel lbl_rep_a;
    private javax.swing.JLabel lbl_rep_e;
    private javax.swing.JLabel lbl_rep_i;
    private javax.swing.JLabel lbl_rep_o;
    private javax.swing.JLabel lbl_rep_u;
    private javax.swing.JLabel lbl_total_de_palabras;
    private javax.swing.JLabel lbl_ultima_letra_del_texto;
    private javax.swing.JLabel lbl_ultima_palabra;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextArea txt_area1;
    private javax.swing.JTextArea txt_area2;
    // End of variables declaration//GEN-END:variables
}
